### ISSUE TITLE
failed to load kernel modul

### ISSUE THREAD

**Issue by jkey** [ljalves/linux_media#117]
i have some issues with loading the kernel module after building

System: Ubuntu 14.04.3 LTS (3.19.0-47-generic)
Hardware: TBS 6982 (SAA7160 rev 03)

demsg log
[demsg_log.txt](https://github.com/ljalves/linux_media/files/109000/demsg_log.txt)

**Comment by BBUK** [comment]
Hi jkey.

See the Wiki: [https://github.com/ljalves/linux_media/wiki/Installating](url)

Rgds

**Comment by jkey** [comment]
Sorry i forgot `sudo make rmmod`

Thx a lot
