### ISSUE TITLE
Moving from TBS proprietary drivers?

### ISSUE THREAD

**Issue by dbrb2** [ljalves/linux_media#130]
Afternoon
This isn't an issue as such...can someone shed some light on how to use the open-source drivers on a box where the closed-source TBS drivers have previously been compiled and used...? What is involved in setting which set of drivers are used...

Perhaps slightly academic though, as my attempt to build the open-source drivers gives me:

 CC [M]  /home/cctv/media_build/v4l/uvc_queue.o
  CC [M]  /home/cctv/media_build/v4l/uvc_v4l2.o
  CC [M]  /home/cctv/media_build/v4l/uvc_video.o
/home/cctv/media_build/v4l/uvc_video.c: In function 'uvc_endpoint_max_bpi':
/home/cctv/media_build/v4l/uvc_video.c:1473:7: error: 'USB_SPEED_SUPER_PLUS' undeclared (first use in this function)
  case USB_SPEED_SUPER_PLUS:
       ^
/home/cctv/media_build/v4l/uvc_video.c:1473:7: note: each undeclared identifier is reported only once for each function it appears in
make[3]: **\* [/home/cctv/media_build/v4l/uvc_video.o] Error 1
make[2]: **\* [_module_/home/cctv/media_build/v4l] Error 2
make[2]: Leaving directory `/usr/src/linux-headers-3.19.0-32-generic'
make[1]: *** [default] Error 2
make[1]: Leaving directory`/home/cctv/media_build/v4l'
make: **\* [all] Error 2

Any ideas...?

**Comment by ljalves** [comment]
Hi,
That error was fixed - you should be able to compile the media_tree now.

**Comment by ljalves** [comment]
Oh, about how to select which driver to use: you can't... you either install and use closed source, or re-install opensource drivers.
