### ISSUE TITLE
TBS6285 symbolrate 0

### ISSUE THREAD

**Issue by Pastinakel** [ljalves/linux_media#39]
Thank you so much for making this driver.

In order to make it work, I had to adjust the symbolrate in the tvheadend mux file. Tvheadend does not give me the option to choose a symbolrate > 0. I think this is related to the symbolrate as reported by the driver: (based on this thread: https://tvheadend.org/issues/1567)

pvr:~# dvb-fe-tool -g
INFO     Device Silicon Labs Si2168 (/dev/dvb/adapter0/frontend0) capabilities:
INFO          CAN_2G_MODULATION
[...]
INFO     Got parameters for DVBC/ANNEX_A:
[...]
INFO     FREQUENCY = 0
INFO     MODULATION = QPSK
INFO     INVERSION = OFF
INFO     SYMBOL_RATE = 0
INFO     INNER_FEC = NONE
INFO     DELIVERY_SYSTEM = DVBC/ANNEX_A

**Comment by ljalves** [comment]
I'm closing this issue since the demod and tuner drivers are in the main kernel tree.
Also I think I saw some patch being submitted to the list that was adding this.
