### ISSUE TITLE
TBS6985 continuity errors when switching channels

### ISSUE THREAD

**Issue by kvaster** [ljalves/linux_media#47]
Latest update is really good for tbs6985. There is no more continuity errors while using all 4 tuners when there is no channel switch. Maybe there is a way to get rid of all issues on 'software level'...

Watch one channel on first tuner, then launch second channel (on another transponder) on second tuner. I can watch both channels without errors for long time, but continuity errors appears immediatelly on first (or second) tuner in case I'm switching to another channel on second (or first).

**Comment by ljalves** [comment]
From user reports, this issue was proven exist on some motherboard chipsets.
Closing this issue as I don't plan to fix it.
