### ISSUE TITLE
Firmware - TBS 6285

### ISSUE THREAD

**Issue by bpbastos** [ljalves/linux_media#54]
Hello,

First of all I'd like to thank ljalves for his great work!

I'm trying to use this driver with my TBS6285 (rev02) on a DVB-C provider but I can't find the right firmware. I've tried the firmwares suggested in the wiki but without success. The most strange is according to dmesg the driver and firmware are loaded ok but as soon as I try to use the adapter the systems crash.

**Comment by ljalves** [comment]
@bpbastos, any news from your side?

**Comment by bpbastos** [comment]
@ljalves 
No, I still can't get tbs 6285 working with intel_iommu=on enabled. 
My main ideia was use it in a kvm vm, but it seems it is impossible, even at the host the card stops working after some minutes with iommu on.

**Comment by ljalves** [comment]
Closing old issue.
Re-open if you have any news about it.
