### ISSUE TITLE
TBS 5922 with Openelec on Raspberry Pi B+

### ISSUE THREAD

**Issue by BTopbas** [ljalves/linux_media#55]
Hi developers! I am very grateful for your hard works. My problem is i ahve raspberry pi and i love my pi. (Ambilight and other great stuffs on pi). I have tbs 5922 usb device. And i love openelec system. I use special building image for raspberry pi. Build is use this repostory and i have issue with this. I dont know maybe other issue. Dmesg output is here 

[   10.574942] dvb-usb: found a 'TBS QBOX22 DVBS2 USB2.0' in cold state, will try to load a firmware
[   10.628633] usb 1-1.4: Direct firmware load for dvb-usb-tbsqbox-id5922.fw failed with error -2
[   10.628660] dvb-usb: did not find the firmware file. (dvb-usb-tbsqbox-id5922.fw) Please see linux/Documentation/dvb/ for more details on firmware-problems. (-2)
[   10.628829] usbcore: registered new interface driver tbsqbox22
[   10.636897] usbcore: registered new interface driver snd-usb-audio

whats problem? 5922 is unsupported arm system like raspberry pi?

**Comment by saeedmou** [comment]
@BTopbas , @mpmc 
hi guy, i compiled my own raspian with CONFIG_I2C_MUX enabled and compile this driver, but i couldn`t load the module. here is the issue: https://github.com/ljalves/linux_media/issues/51
if you done this, plz make a installation guide. :)

**Comment by alessandro-dallatorre** [comment]
Hi guys, 
I have a TBS 5922SE and a Raspberry Pi 2. I'm trying to compile the linux_media drivers with no success (kernel headers not found, dependencies of a previous toolchain gcc 4.7), so I stopped and I wanted to download this raspberry pi Openelec build with tbs 5922 driver. Could anyone please help me by providing a working link to this Openelec build?

**Comment by mpmc** [comment]
@alessandro-dallatorre 

I managed to get it working look at my comment on #101

**Comment by ljalves** [comment]
Closing old issue.
Re-open if needed.

**Comment by mpmc** [comment]
I'd completely forgot about the TBS5922, I shall have to build again to see if it still works!

Thanks for the reminder @ljalves !
