### ISSUE TITLE
TBS-6285 - 'frontend 0 attach failed`

### ISSUE THREAD

**Issue by ChristopherHackett** [ljalves/linux_media#58]
I have a XenServer and have set up PCI pass through for my TBS-6285 tuner. I followed the install instructions but the frontend is not attached for some reason. Have I missed something?

``/dev/dvb/`` is present and when I list one of the 4 adaptors  I get ``ls /dev/dvb/adapter0/``

```
root@debian-tv-data:~# ls -al /dev/dvb/adapter0/
total 0
drwxr-xr-x 2 root root     100 Dec 10 16:57 .
drwxr-xr-x 6 root root     120 Dec 10 16:57 ..
crw-rw---T 1 root video 212, 0 Dec 10 16:57 demux0
crw-rw---T 1 root video 212, 1 Dec 10 16:57 dvr0
crw-rw---T 1 root video 212, 2 Dec 10 16:57 net0
```

When checking ``lspci -v`` I notice no kernel modules are used (but the driver is)
```
# 
00:00.0 Multimedia controller: Philips Semiconductors SAA7160 (rev 02)
Subsystem: Device 6285:0001
Flags: bus master, fast devsel, latency 0, IRQ 26
Memory at fdd00000 (64-bit, non-prefetchable) [size=1M]
Capabilities: [40] MSI: Enable- Count=1/32 Maskable- 64bit+
Capabilities: [50] Express Endpoint, MSI 00
Capabilities: [74] Power Management version 2
Capabilities: [80] Vendor Specific Information: Len=50 <?>
Capabilities: [100] Vendor Specific Information: ID=0000 Rev=0 Len=088 <?>
Kernel driver in use: SAA716x Budget
```

In ``dmesg`` it says that ``frontend n attach failed`` but not why
```
[    3.445054]  c1a2c05c5965c0c8abae0d1d0feb058f73a6b6da Fix sta090x+saa716x bas
ed cards and a bad auto-merge
[    3.493507] SAA716x Budget 0000:00:00.0: enabling device (0000 -> 0002)
[    3.493763] SAA716x Budget 0000:00:00.0: Xen PCI mapped GSI16 to IRQ26
[    3.494156] SAA716x Budget 0000:00:00.0: setting latency timer to 64
[    3.512701] DVB: registering new adapter (SAA716x dvb adapter)
[    3.518146] SAA716x Budget 0000:00:00.0: TurboSight TBS 6285 frontend 0 attach failed
[    3.518595] DVB: registering new adapter (SAA716x dvb adapter)
[    3.523996] SAA716x Budget 0000:00:00.0: TurboSight TBS 6285 frontend 1 attach failed
[    3.524471] DVB: registering new adapter (SAA716x dvb adapter)
[    3.529901] SAA716x Budget 0000:00:00.0: TurboSight TBS 6285 frontend 2 attach failed
[    3.530350] DVB: registering new adapter (SAA716x dvb adapter)
[    3.535223] SAA716x Budget 0000:00:00.0: TurboSight TBS 6285 frontend 3 attach failed
```

**Comment by ljalves** [comment]
To simplify things I've added a link to the OE firmware on the wiki.
Thanks @trsqr and @bas-t for the contribution.

**Comment by johnjohngc** [comment]
Hello,

I also have a tuner card TBS-6285 (revision 21).
I have a server running XenServer 6.5.
I tried to configure the card in PCI passtrough on a virtual machine in Windows 8.1 Pro x64, unfortunately it is not detected in my virtual machine.

Here's what I get when I execute the command "lspci"

----------------------------------------------
03:00.0 PCI bridge: Pericom Semiconductor Device 2304 (rev 05)
04:01.0 PCI bridge: Pericom Semiconductor Device 2304 (rev 05)
04:02.0 PCI bridge: Pericom Semiconductor Device 2304 (rev 05)
05:00.0 Multimedia controller: Philips Semiconductors SAA7160 (rev 02)
----------------------------------------------

For this I followed this tutorial:
http://www.sotechdesign.com.au/xenserver-6-2-how-to-set-up-passthrough-of-a-pci-or-pci-express-device/

I also try to add all the pci card, as shown here:
http://www.sotechdesign.com.au/xenserver-6-2-passing-through-multiple-pci-or-pci-express-devices-to-a-virtual-machine-vm/

I changed my file "extlinux.conf" like this:

----------------------------------------------
label xe
  # XenServer
  kernel mboot.c32
  append /boot/xen.gz dom0_mem=2048M,max:2048M watchdog dom0_max_vcpus=6 crashkernel=128M@32M cpuid_mask_xsave_eax=0 console=vga vga=mode-0x0311 --- /boot/vmlinuz-3.10-xen root=LABEL=root-wiwdkvhp ro hpet=disable xencons=hvc console=hvc0 console=tty0 quiet vga=785 splash pciback.hide=(05:00.0) --- /boot/initrd-3.10-xen.img
----------------------------------------------

I linked the card to my virtual machine like this:

----------------------------------------------
xe vm-param-set other-config:pci=0/0000:05:00.0 uuid=54a0586d-b735-1511-3fda-a1b436f29e3c
----------------------------------------------

Can you help me? it is necessary that I change the firmware of my tuner card?
If so which one should I choose and how to perform this procedure?

Thank you very much for your help.
