### ISSUE TITLE
Instructions when upgrade kernel

### ISSUE THREAD

**Issue by wheatpark** [ljalves/linux_media#59]
Firstly, I'd like to say thanks for supporting this card and helping the open source community.

Probably I'm being a noob but when I update the kernel of my linux server, the drivers for my TBS6280 which previously worked just fine (exceptionally well in fact) stop working.

I have tried following the instructions at
http://linuxtv.org/wiki/index.php/TBS6280#Making_it_Work_.28Open_source.29
and
https://github.com/ljalves/linux_media/wiki/Installating

but it does not build correctly.

Any advice?

Thanks

**Comment by 750430** [comment]
Hi, sorry to hijack your thread, what OS/distro are you using? cheers ;)
