### ISSUE TITLE
 tas2101_get_i2c_adapter  undefined in saa716x_budget

### ISSUE THREAD

**Issue by taktiker12** [ljalves/linux_media#60]
hi 
while trying to compile the drivers i get the following error 

ERROR: "tas2101_get_i2c_adapter" [drivers/media/pci/saa716x/saa716x_budget.ko] undefined!
 
any suggestions 
thank you

**Comment by ljalves** [comment]
Closing this issue (@taktiker12 doesn't answer).
@willat8 thanks for the contribution.
