### ISSUE TITLE
Kernel NULL pointer deref with TBS 6285

### ISSUE THREAD

**Issue by epon** [ljalves/linux_media#61]
Hi,

I'm having problems getting the module working with a TBS 6285 card.

I've built the source successfully and am currently using the firmware from https://github.com/bas-t/media_tree/tree/personal/firmware_extra in my /lib/firmware directory.

When I try to tune in TVHeadend I get:

<pre>
Dec 31 20:34:27 main tvheadend[4665]: dvb: Adapter "Silicon Labs Si2168" Enabled
Dec 31 20:34:27 main tvheadend[4665]: dvb: Adapter /dev/dvb/adapter0 will run in full mux mode
Dec 31 20:34:28 main kernel: [  783.388828] si2157 3-0062: found a 'Silicon Labs Si2146/2147/2148/2157/2158' in cold state
Dec 31 20:34:28 main kernel: [  783.834723] si2157 3-0062: downloading firmware from file 'dvb-tuner-si2158-a20-01.fw'
Dec 31 20:34:49 main kernel: [  804.682376] BUG: unable to handle kernel NULL pointer dereference at           (null)
Dec 31 20:34:49 main kernel: [  804.682403] IP: [<          (null)>]           (null)
</pre>

at which point TVHeadend hangs.

I'm using 3.16.5-gentoo kernel and have disabled multimedia support.

<pre>
$ cat /sys/module/saa716x_budget/parameters/int_type
1
</pre>

I've also tried powering down the system and leaving it for a while to ensure the firmware can be uploaded.

What am I doing wrong?

**Comment by epon** [comment]
@JohnFlowerful 

"You should have removed the old drivers before installing the new ones >_>"

I did of course. I made very sure that the ebuild I created for the official drivers installs into /lib/modules/<kernel_ver>/dvb. This directory was removed before I attempted creating the ebuild for these drivers which install into a different directory as well.

**Comment by ljalves** [comment]
@epon, closing this issue.
Feel free to reopen if needed.
