### ISSUE TITLE
make menuconfig & SAA7160/1/2 based Budget PCIe cards (DVB only) & Autoselect ancillary drivers

### ISSUE THREAD

**Issue by RayCic** [ljalves/linux_media#69]
If in menuconfig I select:
Multimedia support  ---> Autoselect ancillary drivers (tuners, sensors, i2c, frontends)
and select single driver:
Multimedia support  ---> Media PCI Adapters  ---> Support for SAA716x family from NXP/Philips  ---> SAA7160/1/2 based Budget PCIe cards (DVB only)
then after build & install on "modprobe saa716x_budget" I receive:
saa716x_budget: Unknown symbol tas2101_get_i2c_adapter (err 0)

**Comment by ljalves** [comment]
Should be fixed in 0e23e6e54e84f8be279116a47d296e8b2c1b156c

**Comment by RayCic** [comment]
Ok. It looks fixed.

Thank you!
