### ISSUE TITLE
TBS 5990

### ISSUE THREAD

**Issue by adrianhirst** [ljalves/linux_media#76]
These driver currently don't work with the TBS 5990.

Is there any chance of getting them to work?

I would be happy to help with any info etc...

**Comment by ljalves** [comment]
You should first try to find out what chips the card uses for demodulator and tuner.
Since it is a dvb-s/s2 card I would say it uses the tas2101/av2010 combo, but you need to confirm.

**Comment by ljalves** [comment]
No response from @adrianhirst...
Closing this request.
