### ISSUE TITLE
Make failing with rmmod.pl

### ISSUE THREAD

**Issue by stevellion** [ljalves/linux_media#8]
Reporting problem with Line 4 - proc/...

I could still make install afterwards as the modules were build, but the rmmod part of the make had an issue.

Ubuntu 13.04 - Kernel 3.8.0-30-generic

**Comment by momomo** [comment]
You might consider adding a requirements thing to the readme. So that after 20 minutes of building you don't run into this issue.

**Comment by momomo** [comment]
These are all requirements and errors I've run into on a newly fresh server: 

apt-get install make
apt-get install patchutils
apt-get install gcc
apt-get install libproc-processtable-perl

so far ... not done yet.
