### ISSUE TITLE
Card mixing possible?

### ISSUE THREAD

**Issue by decibel83** [ljalves/linux_media#85]
Hi.
I own a TBS6285 and with the official TBS Linux drivers I cannot mix other DVB-T card (Hauppauge WinTV-HVR 1100) in the same system.
Will it be possible with your opensource drivers?

**Comment by ljalves** [comment]
If the Hauppauge WinTV-HVR 1100 is supported by the linux media tree, then yes both will work.

**Comment by ljalves** [comment]
Not sure if you did try my media tree, but the short answer is "yes".
