### ISSUE TITLE
Support for TBS 5220

### ISSUE THREAD

**Issue by adaasch** [ljalves/linux_media#86]
Is there support for TBS 5220 USB Stick? 
If not I could help with device and hacking if someone gives me an entry point.

**Comment by ljalves** [comment]
If I'm not mistaken, the 5220 uses de silabs chips already open source'ed.
It should be very easy to add support to card.

**Comment by adaasch** [comment]
Yes, it has an Cypress CY7C68013A USB bridge and a SiLabs Si2168 DVB Chip on it.

**Comment by ljalves** [comment]
@adaasch, still interested on adding support for that card?

**Comment by adaasch** [comment]
@ljalves, yes, I am. What are the steps?

**Comment by nereeb** [comment]
does this stick have the same components as the geniatech t230?
Can I try echo 734c 5220 > /sys/bus/usb/drivers/??/new_id?
which module should I modprobe to do this?

**Comment by chipsugar** [comment]
It doesn't work. cxusb is the module to modprobe but that fails to do anything. I'm no coder but I think actual support needs to be added for this device, rather than just a new id.

**Comment by nereeb** [comment]
I had figured that out also the dvb_usb_dvbsky for tchnotrend 4400 did not work. So we have to wait and see if someone can add support.

**Comment by nereeb** [comment]
The TBS5220 is working with https://github.com/crazycat69/linux_media

**Comment by ljalves** [comment]
PR #112 merged: adds support for tbs5220.
Thanks CrazyCat.
