### ISSUE TITLE
Digital Devices drivers

### ISSUE THREAD

**Issue by CReimer** [ljalves/linux_media#92]
Hi,

i just stumbled across your repository and it looks quite promising.

I'm wondering if you plan to add other drivers which aren't upstreamed yet. Like the most recent drivers of Digital Devices. http://download.digital-devices.de/download/linux/

There's already a set of patches to make the dddvb drivers compatible with an upstream media_tree repository. http://linuxtv.org/hg/~endriss/media_build_experimental/file/1969cdc5388b/experimental/patch.d

I don't think there's much work remaining to add this to your repository.

My main question is: Would you accept a pull request which adds these drivers? Or do you want to add them yourself?

Thanks

**Comment by ljalves** [comment]
I don't wan't to merge stuff that is in the way to be upstreamed to avoid merge conflicts (want to avoid extra work when merging upstream tree back in here).

For anything else not planned to go upstream, PR are welcome!
