### ISSUE TITLE
Support for Pinnacle PCTV 7010iX

### ISSUE THREAD

**Issue by LeoVerto** [ljalves/linux_media#99]
This is a hybrid DVB-S and DVB-T PCIe card using the NXP SAA716x.

The LinuxTV [wiki page](http://linuxtv.org/wiki/index.php/Pinnacle_PCTV_7010iX) mentions a saa716x_hybrid patch that was unfortunately never released.

If you need further outputs or tests to be run on the card, I'll gladly provide that.

**Comment by ljalves** [comment]
I have no clue about what and where is that patch...
Is someone finds it, feel free to send a PR.
